[font]
size = 17
normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[scrolling]
history = 10000

[window]
dimensions = { columns = 80, lines = 25 }
opacity = 0.8
padding = { x = 10, y = 6 }

[cursor]
style = { blinking = "On" }
blink_interval = 300

[colors.primary]
foreground = "#33cc33"
background = "#000000"
