import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]

[font]
size = 15
normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[scrolling]
history = 20000

[window]
dimensions = { columns = 95, lines = 27 }
opacity = 0.8
padding = { x = 2, y = 2 }
dynamic_padding = true
decorations = "None"

[cursor]
style = { blinking = "On" }
blink_interval = 300

[colors]
# transparent_background_colors = true
